export default {
  add: "mdi-plus",
  arrow_drop_down: "mdi-menu-down",
  check: "mdi-check-circle",
  close: "mdi-close-circle-outline",
  delete: "mdi-delete",
  discord: "mdi-discord",
  error: "mdi-alert-circle",
  info: "mdi-information",
  keyboard_arrow_down: "mdi-chevron-down",
  lock: "mdi-lock",
  lock_open: "mdi-lock-open",
  menu_dots: "mdi-dots-vertical",
  refresh: "mdi-refresh",
  slack: "mdi-slack",
  success: "mdi-check-circle",
  twitter: "mdi-twitter",
  update: "mdi-cached",
  wallet: "mdi-wallet",
  warning: "mdi-alert"
};
