export default {
  add: "mdi-plus",
  admin: "mdi-shield-account",
  arrow_drop_down: "mdi-menu-down",
  check: "mdi-check-circle",
  claims: "mdi-account-cash",
  close: "mdi-close",
  delete: "mdi-delete",
  discord: "mdi-discord",
  disconnect: "mdi-wallet-outline",
  edit: "mdi-pencil",
  error: "mdi-alert-circle",
  info: "mdi-information",
  keyboard_arrow_down: "mdi-chevron-down",
  lock: "mdi-lock",
  lock_open: "mdi-lock-open",
  menu_dots: "mdi-dots-vertical",
  pending: "mdi-timer-sand",
  refresh: "mdi-refresh",
  slack: "mdi-slack",
  success: "mdi-check-circle",
  twitter: "mdi-twitter",
  email: "mdi-email",
  update: "mdi-cached",
  wallet: "mdi-wallet",
  warning: "mdi-alert",
  search: "mdi-magnify",
};
